<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.102.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />

		<PackageReference Include="MahApps.Metro" Version="2.4.10" />
		<PackageReference Include="MahApps.Metro.IconPacks.Material" Version="4.11.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MetGlobalCompany.Application\MetGlobalCompany.Application.csproj" />
		<ProjectReference Include="..\MetGlobalCompany.Infrastructure\MetGlobalCompany.Infrastructure.csproj" />
	</ItemGroup>

</Project>